### ISSUE TITLE
Issues forking for new community

### ISSUE THREAD

**Issue by ashears** [kortina/bailout-nyc#10]
Hello!

I am looking to fork this project for a local community (Eugene, Oregon)

Setting up most of the project has been straightforward. The last hurdle I seem to have is getting the google spreadsheet synced to the application.

I created the columns exactly as specified.

One thing I noticed in index.html is the following
`    var JSON_URL = https://spreadsheets.google.com/feeds/cells/${SPREADSHEET_ID}/1/public/full?alt=json`

When I tied accessing this url, it gave me this error:
> We're sorry. This document is not published.

Is there another step that I am missing ?

**Comment by ashears** [comment]
I was able to resolve my issue. I will be submitting a pull request to add the fix to the documentation incase others wish to fork.

**Comment by jrb2137** [comment]
Hi Ashton,

That's great you're going to set this up for Eugene!

Have you published the google sheet to the web? If not, that's likely the issue (sorry we forgot to include this in the readme ... I'll add now). 

To do this, go to File > Publish to web > Publish.

Let us know if that does the trick.

Jesse

**Comment by jrb2137** [comment]
Just saw your other comment - great, go for it.

**Comment by ashears** [comment]
I appreciate it -- I submitted the pull request and will close this issue.

I would like to ask though, do you have any tips on how to use such a platform to help people?
