### ISSUE TITLE
Open in app

### ISSUE THREAD

**Issue by stdoyle** [kortina/bailout-nyc#14]
Hi. I'm having an issue on mitten.services with the Venmo referring link not processing. 

Here are the screen shots of the errors. Any ideas on what I'm doing wrong?

(Apologies, my Dev/Debugging skills are about 1.5 out of 100) 

Thanks, Shane

![IMG_3197](https://user-images.githubusercontent.com/486546/78048645-03fd6880-7348-11ea-8000-200a66e6f25e.PNG)
![IMG_3196](https://user-images.githubusercontent.com/486546/78048653-08c21c80-7348-11ea-8f6f-fcb2c4face0b.PNG)
![IMG_3195](https://user-images.githubusercontent.com/486546/78048658-095ab300-7348-11ea-810f-ac22cc9c2135.PNG)

**Comment by kortina** [comment]
I am pretty sure this is because there is an `@` in the username. Try changing the payment link so there is no `@` in the username. 

Also, can you post the payment link you are using in the comments here to confirm?

**Comment by kortina** [comment]
See if you use this one: https://venmo.com/bradley-cousens?txn=pay&note=Support%20nyc%20service%20workers%20on%20http://bailout.nyc%20%E2%9D%A4%EF%B8%8F

It will say the full name of the recipient on the page, not the `@` name:

![image](https://user-images.githubusercontent.com/5924/78202355-f085f680-7448-11ea-82b9-6775cc00f58c.png)

**Comment by stdoyle** [comment]
> I am pretty sure this is because there is an `@` in the username. Try changing the payment link so there is no `@` in the username.
> 
> Also, can you post the payment link you are using in the comments here to confirm?

Thanks Andrew, I can't believe it was that simple. Thank you for putting this together. 🧤
